// Copyright (c) 2024 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter/src/widgets/navigator.dart';
import 'package:flutter_thrio/flutter_thrio.dart';

import 'home.page.dart';

class Module with ThrioModule, ModuleParamScheme, ModulePageBuilder, 
ModuleRouteBuilder,ModulePageObserver, NavigatorPageObserver, ModuleRouteObserver, NavigatorRouteObserver {
  @override
  String get key => 'home';

  @override
  Future<void> onModuleInit(ModuleContext moduleContext) async {
    // 可进行模块的一些初始化操作
    ThrioLogger.v('flutter1===> init');
    return;
  }

  @override
  void onPageBuilderSetting(final ModuleContext moduleContext) =>
      pageBuilder = (settings) => HomePage(
            moduleContext: moduleContext,
            settings: settings,
          );

  @override
  void onParamSchemeRegister(final ModuleContext moduleContext) {
    registerParamScheme<String>('stringKeyBiz1');
  }

  @override
  void onRouteBuilderSetting(ModuleContext moduleContext) {
    // 如果实现了此RouteBuilder，则优先会取这里的NavigatorRoute
    // 如果没实现，则ReceiveChannel的push会默认组装一个NavigatorPageRoute执行
     routeBuilder = (pageBuilder, settings) => NavigatorPageRoute(pageBuilder: pageBuilder, settings: settings);
  }

  @override
  void onPageObserverRegister(ModuleContext moduleContext) {
      registerPageObserver(this);
  }

  // @override
  // void willAppear(RouteSettings routeSettings) {
  //   ThrioLogger.v('flutter1===> willAppear');
  // }

  // @override
  // void willDisappear(RouteSettings routeSettings) {
  //   ThrioLogger.v('flutter1===> willDisappear');
  // }

  @override
  void didAppear(RouteSettings routeSettings) {
    ThrioLogger.v('flutter1===> Appear');
  }
  
  @override
  void didDisappear(RouteSettings routeSettings) {
    ThrioLogger.v('flutter1===> Disappear');
  }

  @override
  void onRouteObserverRegister(ModuleContext moduleContext) {
    registerRouteObserver(this);
  }

  @override
  void didPush(RouteSettings routeSettings) {
    ThrioLogger.v('flutter1===> didPush');
  }

  @override
  void didPop(RouteSettings routeSettings) {
    ThrioLogger.v('flutter1===> didPop');
  }

}
