// Copyright (c) 2024 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter/material.dart';
import 'package:flutter_thrio/flutter_thrio.dart';

import 'flutter3.page.dart';

class Module with ThrioModule, ModulePageBuilder, ModuleRouteTransitionsBuilder{
  @override
  String get key => 'flutter3';

  @override
  void onPageBuilderSetting(final ModuleContext moduleContext) =>
      pageBuilder = (settings) => Flutter3Page(
            moduleContext: moduleContext,
            settings: settings,
          );

  @override
  void onRouteTransitionsBuilderSetting(ModuleContext moduleContext) {
    routeTransitionsBuilder = (
          context,
          animation,
          secondaryAnimation,
          child,
        ) =>
            SlideTransition(
              transformHitTests: false,
              position: Tween<Offset>(
                begin: const Offset(0, -1),
                end: Offset.zero,
              ).animate(animation),
              child: SlideTransition(
                position: Tween<Offset>(
                  begin: Offset.zero,
                  end: const Offset(0, 1),
                ).animate(secondaryAnimation),
                child: child,
              ),
            );
  }
}
